using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using frontend.Annotations;
using frontend.Commands;
using frontend.Navigation;
using Serilog;

namespace frontend.ViewModels
{
    /// <summary>
    /// ViewModel for MainWindow
    /// </summary>
    public class HomeViewModel : ViewModelBase
    {

        public ObservableCollection<Route> Routes { get; set; }
      
        public HomeViewModel()
        {
            Log.Debug("CTOR HomeViewModel");
            Routes = new ObservableCollection<Route>();
            Routes.Add(new Route { Name = "Route1", Description = "beschreibungbeschreibungngbeschreibungbeschreibungbeschreibubeschreibubeschreibungbeschreibungbeschrebubeschreibubeschreibungbeschreibungbeschreibbubeschreibubeschreibungbeschreibungbeschreibibung", Id = 1 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 }); 
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 }); 
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 }); 
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 }); 
            Routes.Add(new Route { Name = "Route2", Description = "beschreibung", Id = 2 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
            Routes.Add(new Route { Name = "Route3", Description = "beschreibung", Id = 3 });
        }
    }
}